### ISSUE TITLE
Request: add timer

### ISSUE THREAD

**Issue by DarrenPIngram** [PranavMahesh1/reddit-user-comment-deleter-by-subreddit#1]
This looks to be a very useful thing. There's just one feature I'd like to try (well two perhaps, the first is more important) if it would be easy for you to implement, and you are willing to do it.

1. Add a timer that is configurable, e.g. 30 days. Then the script will delete comments OLDER than 30 days at the time of running.
2. Ability to add a number of subreddits in the same configuration file, so one could even script this to run every month for a bit of a clean-up.

Thanks for any consideration.

**Comment by PranavMahesh1** [comment]
I've incorporated both suggestions in the latest commit! https://github.com/PranavMahesh1/reddit-user-comment-deleter-by-subreddit/commit/766099d3fe9d83f1efac4f70ed1e831ad94987c3

Now, you can specify to delete comments older than X days in the ``TIMER`` variable. I've also changed ``SUBREDDIT`` to be an array, so you can now add a number of subreddits to delete posts and comments from!

Thanks for the suggestions :)
