### ISSUE TITLE
Possible feature: delete from archive sources

### ISSUE THREAD

**Issue by DarrenPIngram** [PranavMahesh1/reddit-user-comment-deleter-by-subreddit#2]
Reading this thread made me wonder if there is scope for (and API support) to possible request deletion from services that archive Reddits?

https://www.reddit.com/r/DataHoarder/comments/qlpxrs/question/

**Comment by PranavMahesh1** [comment]
I don't think that's possible - we can't delete data off an archive. Pushshift allows you to fill out their own form for you to request your data to be hidden. I don't know if there are any other archive services though.

**Comment by DarrenPIngram** [comment]
Understand. Just threw it out there in case it might be an option. The
script already is awesome!

‌

**Comment by PranavMahesh1** [comment]
Glad you like it!
