### ISSUE TITLE
0 comments detected from /r/XXX.

### ISSUE THREAD

**Issue by seralouk** [PranavMahesh1/reddit-user-comment-deleter-by-subreddit#3]
The current code seems to not be working as it always returns:

```
0 comments detected from /r/XXX.
```

**Comment by PranavMahesh1** [comment]
I just tried the script on a random account and it was able to get the list of comments/posts. The comments/posts I get are all from Pushshift, so it's possible the account you're looking for doesn't have anything stored in their database for some reason. 
Try seeing if anything is returned by this search here, which also uses Pushshift: https://camas.unddit.com/
